spring:
    config:
        activate:
            on-profile: local
    datasource:
        hikari:
            driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
            jdbc-url: jdbc:log4jdbc:mysql://127.0.0.1:3306/dailyPT?characterEncoding=utf8&autoReconnect=true&useSSL=false
            username: root
            password: password
            pool-name: dailyPT-local
            minimum-idle: 2
            maximum-pool-size: 2
            validation-timeout: 1000
            connection-timeout: 3000
            max-lifetime: 600
    jpa:
        database: mysql
        open-in-view: false
        hibernate:
            ddl-auto: update
        decorator:
            datasource:
                p6spy:
                    enable-logging: true